#!/usr/bin/sh
set -eu

id="$(xprop -root _NET_ACTIVE_WINDOW)"
id="${id##* }"
vm="$(xprop -id "$id" | grep '_QUBES_VMNAME(STRING)')" || true
if test -z "$vm"; then
exec echo $vm
fi
vm="${vm#*\"}"
vm="${vm%\"*}"

exec echo $vm
